# Generated by Django 4.2.7 on 2023-11-24 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_section_subsection_header_footer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='adress_name',
            new_name='address_name',
        ),
        migrations.AlterField(
            model_name='footer',
            name='address',
            field=models.ForeignKey(blank=True, limit_choices_to={'address_name': 'Website_Kontakt_Adres'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.address'),
        ),
    ]
