# Generated by Django 4.2.7 on 2023-11-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_adress_name_address_address_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_name_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='address_name_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='city_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='city_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='country_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='country_tr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='line1_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='line1_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='title_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='header',
            name='title_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='description_tr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='name_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subsection',
            name='name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subsection',
            name='name_tr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='universalsetting',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universalsetting',
            name='description_tr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universalsetting',
            name='value_ru',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='universalsetting',
            name='value_tr',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
