# Generated by Django 4.2.5 on 2023-11-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllEvents', '0002_event_description_ru_event_description_tr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_tr',
            field=models.TextField(null=True),
        ),
    ]
