# Generated by Django 4.2.5 on 2023-11-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllEvents', '0003_alter_event_description_alter_event_description_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='html_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='html_content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='html_content_tr',
            field=models.TextField(null=True),
        ),
    ]
