# Generated by Django 4.2.5 on 2023-11-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllEvents', '0004_alter_event_html_content_alter_event_html_content_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='symbolic_image_url',
            field=models.URLField(blank=True),
        ),
    ]
