# Generated by Django 4.2.5 on 2023-11-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllPageInformations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basefooter',
            name='locale',
            field=models.CharField(default='tr', help_text='Locale for multi-language support', max_length=10),
        ),
    ]
