# Generated by Django 4.2.5 on 2023-11-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllPageInformations', '0002_alter_basefooter_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbarbrand',
            name='link_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='navbarbrand',
            name='link_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='link_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='link_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='subsection',
            name='link_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='subsection',
            name='link_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='subsubsection',
            name='link_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='subsubsection',
            name='link_tr',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='navbarbrand',
            name='link',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='section',
            name='link',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='link',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='subsubsection',
            name='link',
            field=models.TextField(),
        ),
    ]
