# Generated by Django 4.2.5 on 2023-11-20 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AllPageInformations', '0003_navbarbrand_link_ru_navbarbrand_link_tr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navbarbrand',
            name='link_ru',
        ),
        migrations.RemoveField(
            model_name='navbarbrand',
            name='link_tr',
        ),
        migrations.RemoveField(
            model_name='section',
            name='link_ru',
        ),
        migrations.RemoveField(
            model_name='section',
            name='link_tr',
        ),
        migrations.RemoveField(
            model_name='subsection',
            name='link_ru',
        ),
        migrations.RemoveField(
            model_name='subsection',
            name='link_tr',
        ),
        migrations.RemoveField(
            model_name='subsubsection',
            name='link_ru',
        ),
        migrations.RemoveField(
            model_name='subsubsection',
            name='link_tr',
        ),
    ]
