# Generated by Django 4.2.5 on 2023-11-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllPageInformations', '0004_remove_navbarbrand_link_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.CharField(max_length=7)),
                ('secondary', models.CharField(max_length=7)),
                ('text', models.CharField(max_length=7)),
                ('header', models.CharField(max_length=7)),
                ('complementary', models.CharField(max_length=7)),
            ],
        ),
    ]
