# Generated by Django 4.2.5 on 2023-11-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllPageInformations', '0005_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='colors',
            name='body_bg',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='colors',
            name='body_color',
            field=models.CharField(default='#212529', max_length=7),
        ),
        migrations.AddField(
            model_name='colors',
            name='danger',
            field=models.CharField(default='#dc3545', max_length=7),
        ),
        migrations.AddField(
            model_name='colors',
            name='dark',
            field=models.CharField(default='#212529', max_length=7),
        ),
        migrations.AddField(
            model_name='colors',
            name='info',
            field=models.CharField(default='#0dcaf0', max_length=7),
        ),
        migrations.AddField(
            model_name='colors',
            name='light',
            field=models.CharField(default='#f8f9fa', max_length=7),
        ),
        migrations.AddField(
            model_name='colors',
            name='success',
            field=models.CharField(default='#198754', max_length=7),
        ),
        migrations.AddField(
            model_name='colors',
            name='warning',
            field=models.CharField(default='#ffc107', max_length=7),
        ),
        migrations.AlterField(
            model_name='colors',
            name='complementary',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AlterField(
            model_name='colors',
            name='header',
            field=models.CharField(default='#f8f9fa', max_length=7),
        ),
        migrations.AlterField(
            model_name='colors',
            name='primary',
            field=models.CharField(default='#0d6efd', max_length=7),
        ),
        migrations.AlterField(
            model_name='colors',
            name='secondary',
            field=models.CharField(default='#6c757d', max_length=7),
        ),
        migrations.AlterField(
            model_name='colors',
            name='text',
            field=models.CharField(default='#212529', max_length=7),
        ),
    ]
