# Generated by Django 4.2.5 on 2023-11-21 11:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('AllPageInformations', '0006_colors_body_bg_colors_body_color_colors_danger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='ref_name',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
