# Generated by Django 4.2.5 on 2023-11-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllPageInformations', '0007_image_ref_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024),
        ),
    ]
