# Generated by Django 4.2.5 on 2023-11-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllPageInformations', '0008_image_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSectionTitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_identifier', models.SlugField(help_text='Unique identifier for the section', unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('title_tr', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True, verbose_name='Subtitle')),
                ('subtitle_tr', models.CharField(blank=True, max_length=300, null=True, verbose_name='Subtitle')),
                ('subtitle_ru', models.CharField(blank=True, max_length=300, null=True, verbose_name='Subtitle')),
                ('display_order', models.PositiveIntegerField(help_text='Order in which the section appears on the homepage')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle visibility of this section on the homepage')),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the section was created')),
                ('last_modified_date', models.DateTimeField(auto_now=True, help_text='Timestamp of the last modification')),
                ('icon_class', models.CharField(blank=True, help_text='Class name for the icon', max_length=100, null=True)),
                ('background_image_url', models.URLField(blank=True, help_text='URL of the background image for the section', null=True)),
                ('link_url', models.URLField(blank=True, help_text='URL if the section title links to another page', null=True)),
                ('additional_notes', models.TextField(blank=True, help_text='Any additional notes or instructions', null=True)),
            ],
            options={
                'verbose_name': 'Home Page Section Title',
                'verbose_name_plural': 'Home Page Section Titles',
                'ordering': ['display_order'],
            },
        ),
    ]
